### PR TITLE
added aaronmallen packlist to repolist

### PR DESCRIPTION
**Pull request by aaronmallen**
I have a couple of concerns about my packlist that I'd like to address and possibly repair before you merge this...

1. Does packman expect the file(s) to be there to be successful?  I have this [pastebin](http://pastebin.com/JmprtvzY) as my setup script.  If it detects that CraftOS is > 1.77 it removes my package as it isn't needed.

1. I am assuming that by not specifying a target on settings (which is a file) it will be installed as '/usr/bin/settings' and not 'usr/bin/aaronmallen/settings/settings' is this a correct assumption?

Thanks in advance for your help, and AWESOME project man!

### CODE REVIEW

**Comment by lyqyd** [comment]
Your version of repolist conflicts with the current version, you'll want to merge the latest version of it with the copy on your aaronmallen-packages branch before this PR can be merged.

1. Yes, packman will think that the files exist if your setup script executes successfully. To abort an installation, simply have your setup script error, and packman will realize that the installation has failed and remove the files already installed. However, the setup script is expected to be in the same directory as the rest of the files, so `/usr/bin/pastebin run <code>` isn't going to work. You might want to add a version-check mode to your script that simply errors when the correct version is not found, `settings checkVersion` or similar, and use that as the setup script.

2. That assumption is correct.

**Comment by aaronmallen** [comment]
fixed, fixed, and fixed.

**Comment by aaronmallen** [comment]
as an aside this isn't going to be my only package... I need this particular package for another project I'll be pushing up hopefully this weekend.

**Comment by lyqyd** [comment]
Thanks for the fixes!

**Pull request merged**
