### PR TITLE
Update repolist

### PR DESCRIPTION
**Pull request by MrObsidy**
I added my repository (mrobsidy/technical-data-information/packlist in.

### CODE REVIEW

**Comment by lyqyd** [comment]
Please correct the url (it appears you wanted `https://raw.githubusercontent.com/MrObsidy/technical-data-inf/master/packlist`), and then I will accept the pull request.

**Comment by MrObsidy** [comment]
Okay, I did want that URL and I fixed things up so it should be good

**Comment by lyqyd** [comment]
The pull request isn't showing the new changes.  You'll want to check out your `patch-1` branch and merge in the new commit you made to the `master` branch, then push the updated `patch-1` branch to github, which should update the contents of this pull request.  Sorry to give you the run-around on this one.

**Comment by MrObsidy** [comment]
Okay, i finally updated the patch-1 branch so the file repolist is up to date on both branches (master and patch-1). Should be good.

**Comment by lyqyd** [comment]
Thanks, merged!

**Comment by MrObsidy** [comment]
Thanks a lot, Lyqyd!

**Pull request merged**
